### PR TITLE
Added build for PHP 7.2 to Travis

### PR DESCRIPTION
**Pull request by asgrim**
As it says on the tin.

### CODE REVIEW

**Comment by asgrim** [comment]
Note: build failing at the moment as xdebug is not available on the build environment yet.

**Comment by asgrim** [comment]
MWOP suggested [this approach](https://github.com/zendframework/zend-expressive-hal/blob/master/.travis.yml#L42), tho that wouldn't help with Humbug unless we disable Humbug where xdebug not available

**Comment by Ocramius** [comment]
Not worth testing without humbug, IMO: it can wait until release.

Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/

**Comment by Ocramius** [comment]
@asgrim rebase also needed

**Comment by Ocramius** [comment]
Newer PHPUnit version needed: https://travis-ci.org/Roave/DoctrineSimpleCache/jobs/264439014#L235

**Comment by asgrim** [comment]
Green :green_heart:

**Comment by Ocramius** [comment]
:ship:

**Pull request merged**
