### PR TITLE
When clear, use flush instead of deleteAll

### PR DESCRIPTION
**Pull request by namenu**
Doctrine has "CacheProvider" that gives implementing compatibility layer to every cache types.

Unlike before, CacheProvider has FlushableCache interface so you can clear every items more efficiently.

Also Roave\CacheException is not required for runtime check.

### CODE REVIEW

**Comment by asgrim** [comment]
`flushAll` has a different meaning to `deleteAll`; the implementation was done using `deleteAll` intentionally; PSR-16 does not have an equivalent of `flushAll`, so cannot be exposed this way.

**Comment by namenu** [comment]
Thanks for reviewing. I didn't considered the namespace issue.

Quick question: reverting the clear behavior, still has a reason not to use CacheProvider?

**Comment by asgrim** [comment]
Initially I agree it seems like it's a good fit, but it doesn't allow for cache implementations that don't extend the abstract `CacheProvider`; by requiring specifically the interfaces, I think we leave ourselves open to any implementation (therefore, more usable in general)

**Comment by asgrim** [comment]
Consider:

`final class MyCustomCacheImplementation implements Cache, ClearableCache, MultiGetCache, MultiPutCache`

(this provides all required functionality by the SimpleCache adapter, but would not be allowed if we typed to `CacheProvider`)

Also this would be a BC break.

**Comment by namenu** [comment]
My idea was based on kind of like,
'I will use Doctrine-dependent cache implementations anyway, so why should I care about extensibility?'.

But now I see the difference in perspectives and BC breakage. Thanks 😅

**Comment by asgrim** [comment]
yw! :) thanks for the proposal anyway.

**Pull request closed without merging**
