### PR TITLE
Replace humbug with infection

### PR DESCRIPTION
**Pull request by BackEndTea**
Humbug has been deprecated in favor of infection.

### CODE REVIEW

**Comment by Ocramius** [comment]
Can you check the build failure, please?

**Comment by BackEndTea** [comment]
It looks like we aren't compatible with `symfony/console` 3.2, and actually need 3.4.

I'll try and fix in infection

**Comment by Ocramius** [comment]
Bumping the dependency here is also fine

**Comment by BackEndTea** [comment]
I have bumped the dependency as a (temporary) work-around

**Comment by BackEndTea** [comment]
Thank you @Ocramius

**Comment by Ocramius** [comment]
No, thank YOU for sending the update :-)

**Pull request merged**
